### ISSUE TITLE
ошибки в 2.1-beta

### ISSUE THREAD

**Issue by Tushkan** [alekseybochkov/EventLogLoader#8]
2.1-beta
1. При сохранении параметров для ES в config.json не сохраняется имя индекса
2. На Win2008R2 x64 Server при работе в лог пишет:
```
16.02.2017 10:37:28 (ERROR): Error occurred while working with reference tables. System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at System.Data.SQLite.SQLiteConvert.TypeNameToDbType(SQLiteConnection connection, String typeName, SQLiteConnectionFlags flags)
   at System.Data.SQLite.SQLiteDataReader.GetSQLiteType(SQLiteConnectionFlags flags, Int32 i)
   at System.Data.SQLite.SQLiteDataReader.GetValue(Int32 i)
   at EventLogLoaderService.EventLogProcessor.LoadReference()
```
возможно что-то нужно установить.

**Comment by JohnyDeath** [comment]
А где вообще задается имя индекса?

**Comment by Tushkan** [comment]
@JohnyDeath 
![default](https://cloud.githubusercontent.com/assets/213098/23054762/eb2390ae-f4f2-11e6-979b-c7dd0cc7e2b8.png)
Но он все равно не записывается в config.json - приходиться править руками

**Comment by alex-bochkov** [comment]
@Tushkan 
1) поправил
2) Установлен ли .NET 4.6? 
Спасибо!

**Comment by Tushkan** [comment]
> Установлен ли .NET 4.6?

нет
